---
title: "Наивник ли е Ганя и ако не, то работи ли пропагандата? "
description: |
  Имаме грешната представа за това как се формират убеждения и това ни превръща в твърдоглави, поляризирани сърдитковци.
author:
  - name: Ивайло Сакелариев
    url: {}
date: "`r Sys.Date()`"
base_url: https://ivaylo.xyz
citation: false
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    self_contained: false
csl: apa.csl
bibliography: ivaylo.bib
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Интро

Ах, дезинформацията и пропагандата. Двамата конници на модерния апокалипсис, обвинявани за всичко --- от политическата нестабилност в България до провалът на здравните организации по време на Ковид пандемията. Колко удобно и лесно звучи те да са виновни за всичко, нали?

**Победата на Тръмп през 2016-та?** Разбира се, че се дължи на Cambridge Analytica, руската намеса и милионите фалшиви послания във Фейсбук, които заляха "простичките" американци в месеците преди изненадващата победа на Доналд Тръмп над Хилъри Клинтън.

**Възходът на Възраждане през последните 3 години?** Естествено, че е благодарение на руските тролове, руската пропаганда и липсата на критическо мислене сред повечето българи (често определяни като Ганя в някои онлайн среди).

**Ниският процент ваксинирани в България на фона на другите държави в Европа?** Фалшивите новини и липсата на информираност са често сочени като основни причини за този тотален провал на правителството (правителствата) и здравните институции, който доведе до смъртта на повече от 38 хиляди българи.

За мен доскоро това си бяха съвсем правдоподобни обяснения. Като някой започнал да се интересува от социалните науки през 2016-та година, една от първите научно-популярни книги за психология, които прочетох беше Мисленето на Канеман (Thinking, Fast and Slow). Като някой с един единствен инструмент в репертоара си се опитвах да анализирам всичко, случващо се с хората около мен използвайки Система 1 (бързата, автоматична, "склонна към грешки") и Система 2 (бавната, съзнателна, фокусирана). Когато някой ми кажеше, че има доказателства за това как Земята е плоска, кимах разочаровано с глава -- ясно той просто използва Система 1 и не е прочел, не е информиран, чул го е от някъде и го повтаря, не е спрял да се замисли, няма необходимото познание или най-вероятно [просто е глупав](https://www.ploshtadslaveikov.com/korab-shte-plava-po-ploskata-zemya-za-da-oprovergae-sferichnata-forma/). И така с много други убеждения и идеи :

-   Сорос е виновен за финансовата криза в България през 1997 година → използва Система 1

-   Ваксините имат чипове → използва Система 1

-   Бил Гейтс слага чипове във ваксините → използва Система 1

-   Бил Гейтс изкупува земеделска земя, за да може да контролира света след години, когато настане световния глад → използва Система 1

-   Кемтрейлс (любимата ми конспирация) → използва Система 1

-   Гласува за Възраждане → използва Система 1

-   Харесва или подкрепя Путин → използва Система 1

-   и така нататък
