---
title: "Тестът Myers Briggs – “научният“ хороскоп"
description: |
  Myers-Briggs тестът несъмнено е най-популярният тест за установяване на личностния тип. Дали обаче се справя 
author:
  - name: Ивайло Сакелариев
    url: {}
date: "`r Sys.Date()`"
output: distill::distill_article
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Архитект (**INTJ-A / INTJ-T**)

*Самотно е на върха и, като един от най-редките типове с най-развити стратегически способности, Архитектът отлично знае това. Архитектите формират само два процента от населението, а жените от този тип са особено редки, като представляват само 0,8% от населението -- често за тях е предизвикателство да намерят сходни личности, които могат да са в крак с тяхното неуморно интелектуално маневриране като в игра на шах. Хората с личностен тип Архитект притежават въображение и все пак са решителни; амбициозни, но прикрити; изумително любопитни, без да разпиляват енергията си.*

Това беше първият ми сблъсък с Myers-Briggs теста преди около 13 години, когато с повечето ми съученици правехме различни тестове за кариерно ориентиране, а откъсът е описанието на моят "личностен тип" **INTJ-A / INTJ-T или Архитект. (** [https://www.16personalities.com/bg/личностен-тип-intj](https://www.16personalities.com/bg/%D0%BB%D0%B8%D1%87%D0%BD%D0%BE%D1%81%D1%82%D0%B5%D0%BD-%D1%82%D0%B8%D0%BF-intj)**).** Няма да забравя колко специален и уникален се почувствах, когато прочетох, че принадлежа към една толкова рядка категория "изумително любопитни и амбициозни" хора. 😄

Въпреки голямата си популярност, този тест категорично се проваля при прогнозирането на бъдещо поведение (poor validity) и често дава различни резултати за един и същи човек (poor reliability). В този блог пост ще разгледам Myers-Briggs теста през призмата на няколко различни научни парадигми, за да се убедим как той всъщност е точно толкова полезен колкото астрологията.
