---
title: "Bulgarian spaCy models"
description: |
  Български spaCy модели за анализ на текст
date: 2023-11-28
base_url: https://ivaylo.xyz
preview: images/streamlit_demo.png
output:
  distill::distill_article:
    self_contained: false
---

[SpaCy](https://spacy.io) е безспорно една от най-лесните и функционални библиотеки за работа с език с Python (като цяло, с който и да е език ако питате мен). Българският език все още липсва от [официално поддържаните езици в spaCy](https://spacy.io/models) и едва ли ще се появи официален pipeline в скоро време, заради ограниченият лиценз (CC-BY-NC-SA-3.0) на [българския Treebank](https://universaldependencies.org/treebanks/bg_btb/index.html), който не разрешава използване с комерсиални цели, а от Explosion (създателите на spaCy) вече отказват качването на разработки с толкова ограничен лиценз. И все пак един неофициален български spaCy модел би имал полза поне за образователни или научни цели. Затова създадох три български модела, които включват Named Entity Recognition - функционалност, която липсва в останалите open-source модели за работа с български език.

**Данни**\
Данните, на които е трениран NER модела са извлечени от български онлайн медии, затова и имената на всички модели започват с **bg_news**. В момента NER parser-a е трениран със само три класа - Location, Person и Organisation, но планирам ъпдейти в близките месеци, където освен обновени bg_news модели с нови класове ще добавя и модел комбиниращ данни от правителствени документи, постове в социални мрежи, медийни материали и художествена литература. Освен това търся сигурен вариант, в който да споделя данните без риск от нарушаване на авторски права.

**Лиценз\
**CC-BY-NC-SA-3.0

Повече информация за създаването на моделите и spaCy проекти, за да репликирате резултатите:\
➡️ [Github](https://github.com/sakelariev/bulgarian-spacy-models)

Всички модели може да намерите тук и да инсталирате директно:\
➡️ [Huggingface](https://huggingface.co/sakelariev)
